// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpxnrjddwxkhpygwdooi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpweG5yamRkd3hraHB5Z3dkb29pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NDQ4NDUsImV4cCI6MjA2MzUyMDg0NX0.09WVA6A1CJoK6G0JYmmii-8S1a3EnT1ffSE--8RwqH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);